@echo off
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1
start https://www.youtube.com/watch?v=dQw4w9WgXcQ&autoplay=1